name: Ping FDP index
on:
  # allow workflow to run manually
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout cde model repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # List files
      - name: List repo content
        run: ls
      # run script
      - name: Ping FDP index
        id: ping-index
        working-directory: ./script
        env:
          FDP_INDEX_URL: "https://fdps.ejprd.semlab-leiden.nl/"
          FDP_URL: "https://rajaramzfdp.fdpcloud.org/fdp-content/repository"
        run: pingFdpIndex.sh
